host:        127.0.0.1
port:        4000

name:        "Welcome to my blog"
markdown:    kramdown
highlighter: rouge

permalink:   /blog/:year/:month/:title.html

snow:        0
christmas:   0

plugins:
  - jekyll-redirect-from

collections:
  platforms:
    output: true

